### ISSUE TITLE
Automate the Travis build checks

### ISSUE THREAD

**Issue by mseri** [xapi-project/xs-opam#133]
As suggested by @gaborigloi, the new docker based Travis build allow for a greater flexibility and could be useful for a number of additional automated checks:

- [x] build a container with all xs-opam installed and push it to the docker repository -> done: https://github.com/xapi-project/xs-opam/pull/165
- [ ] build a container without the `upstream` folder, install `xs` and `xs-extra` and check that we have only needed packages in `upstream` and `upstream-extra` -> detecting unused `upstream` packages done: https://github.com/xapi-project/xs-opam/pull/249 , unused `upstream-extra` packages still not detected
- [x] build a container with `xs-opam` as the extra remote and check which packages we can update, presenting the list as the final stage of the Travis build -> https://github.com/xapi-project/xs-opam/pull/223
- [ ] build and push the complete documentation of all the packages we use
- [x] make it possible to build the container locally -> done: https://github.com/xapi-project/xs-opam/pull/170
- [ ] Run all the tests of all the packages
- ...

**Comment by gaborigloi** [comment]
Working on the first item, should send a PR soon. Uploaded the image https://hub.docker.com/r/gaborigloi/xs-opam/ , successfully built `xen-api-client` in it without any extra steps, by just running `make`.

**Comment by gaborigloi** [comment]
Code is on this branch: https://github.com/gaborigloi/xs-opam/tree/push_docker

**Comment by gaborigloi** [comment]
After running `odig odoc`, the index.html and the docs will be in ` $(opam config var prefix)/var/cache/odig/odoc`

**Comment by mseri** [comment]
I have a Travis cron job running nightly to check for updates, I'll move it to this repo later today

**Comment by gaborigloi** [comment]
Closing as we now have a completely different, simplified Travis setup: https://github.com/xapi-project/xs-opam/blob/master/tools/travis.sh 
We should reintroduce the required checks.
I've created #333 for uploading the docs.
We should also add automation to detect unused upstream packages, I've created https://github.com/xapi-project/xs-opam/issues/334 for that
