### ISSUE TITLE
Port to safe strings

### ISSUE THREAD

**Issue by mseri** [xapi-project/xs-opam#238]
The following packages need porting to `safe-string`. Please keep this list updated with the packages that you port and release. Note that some packages could already work with safe-strings, they just need to be marked as such.

From `packages/xs`:

- [x] cdrom
- [x] crc
- [x] ezxenstore.0.2.0
- [x] fd-send-recv
- [x] nbd
- [x] netlink
- [x] opasswd
- [x] qmp
- [x] xapi-backtrace
- [x] xapi-inventory
- [x] xapi-rrd.1.3.0
- [x] xapi-stdext.4.0.0
- [x] xapi-test-utils

From `packages/xs-extra`:

- [x] message-switch.master
- [x] rrd2csv.master
- [x] rrddump.master
- [x] vhd-tool.master
- [ ] vncproxy.master
- [x] wsproxy.master
- [x] xapi-forkexecd.master
- [x] xapi-idl.master
- [x] xapi-libs-transitional.master
- [x] xapi.master (in progress)
- [x] xapi-nbd.master
- [x] xapi-netdev.master
- [x] xapi-networkd.master
- [x] xapi-plugin.master
- [x] xapi-rrdd.master
- [x] xapi-rrdd-plugin.master
- [x] xapi-rrd-transport.master
- [x] xapi-squeezed.master
- [x] xapi-storage-cli.master
- [x] xapi-storage.master
- [x] xapi-storage-script.master
- [x] xapi-tapctl.master
- [x] xapi-xenopsd.master
- [x] xapi-xenops.master
- [x] xen-api-client
- [x] xen-api-sdk.master
- [x] xenctrl.master 

Not in `xs-opam` (due to issues with blktap-devel):

- [x] rrdd-plugins.master (on xenserver/rrdd-plugins)

**Comment by mseri** [comment]
Some comments. Keep in mind that `Bytes.of_string` and `Bytes.string_of` are making copies, if the string is used as a buffer, it has to be `Bytes` from the creation or (if we can easily control its lifetime) it has to be converted using unsafe conversions: please have a look at the relevant section of https://caml.inria.fr/pub/docs/manual-ocaml/libref/Bytes.html for further information on when it is reasonable to use unsafe coercions

**Comment by mseri** [comment]
Some more remarks. If you add `(flags (:standard -safe-string))` in `jbuilder` to compile the packages with safe strings, remember to remove it before doing the pull request. Mixing `-safe-string` flags makes the compiler very unhappy and produces a lot of conflicting interface failures.

To test the changes a new 406 branch has been added to `xs-opam`. You can fork it and enable Travis on your fork, so that you can modify the `url` files to point at your changes and use the Travis build to check them. Travis will perform 4 builds: 2 are checking upstream packages with and without safe-string, and 2 are checking `xs*` packages. The build that disables safe strings has to stay green, the build with safe string will not be green until all our packages are safe-string compiiant but its output can be used to check that things are still fine.

**Comment by mseri** [comment]
Looking at the 406 branch build, it seems that we will need to send also some PRs to fix upstream packages

**Comment by mseri** [comment]
Further updates: we need to modify `ocaml-fd-send-recv` interface

**Comment by lindig** [comment]
I believe this can be closed.
