### ISSUE TITLE
Upgrade to Lwt 4.0

### ISSUE THREAD

**Issue by gaborigloi** [xapi-project/xs-opam#288]

**Comment by edwintorok** [comment]
I think there are some upstream libraries that explicitly have an <Lwt 4.0, we'll probably have to wait until they upgrade.

**Comment by mseri** [comment]
Yes, we cannot update due to either cohttp or conduit not having released the new lwt-4.0.0 compatible version

**Comment by rgrinberg** [comment]
I currently don't have the spare time to move any opam releases. Feel free
to make a release yourself however.

**Comment by mseri** [comment]
Thanks! I wasn't sure if there was anything (like missing features, testing or changes in progress) that were preventing the release

**Comment by lindig** [comment]
I think this is not an issue any more. The master branch of this repository includes Lwt 4.1 and builds on Travis.

**Comment by gaborigloi** [comment]
Thanks for the clarification, I didn't know we'd already upgraded :)

**Comment by lindig** [comment]
We are not using that in production, though as we have not made a release yet.
