### ISSUE TITLE
Build and push the complete documentation of all the packages we use

### ISSUE THREAD

**Issue by gaborigloi** [xapi-project/xs-opam#333]

**Comment by psafont** [comment]
`odig` is now able to build and aggregate all the documentation of the packages in xs-opam. This is after https://github.com/xapi-project/xcp-idl/pull/300 and https://github.com/xapi-project/xapi-storage/pull/107 got merged.

**Comment by psafont** [comment]
Now the documentation of all upstream packages can be found at https://ocaml.org/packages
