### ISSUE TITLE
add new xapi-fd*.opam packages

### ISSUE THREAD

**Issue by edwintorok** [xapi-project/xs-opam#676]
Looks like we'll need to add the new xapi-fdcaps.opam to `xs-opam`, or the CI fails (the downside of not pinning every package anymore, opam doesn't get to know about new local packages).
Tried pinning just the new packages, but that also hides the other packages from opam-depext, resulting in a lot of missing system dependencies, and currently in the ci you can't control the 2 lists separately.

_Originally posted by @edwintorok in https://github.com/xapi-project/xen-api/issues/5629#issuecomment-2111209175_

**Comment by psafont** [comment]
The packages could be added, linking them to the branch. to make it known that these are special packages, they could be placed in the folder `packages/xs-perf/` Since nothing in xapi's master branch not in xs-opam depends on it, the rest of the CI should remain unaffected
